version: '3'
services:
  app:
    container_name: "nodeapp"
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production  # Set your desired environment variables
    volumes:
      - '.:/usr/src/app'
    depends_on:
      - db
  db:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8060:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
volumes:
  db-data: